name-template: '$RELEASE_VERSION'
tag-template: '$RELEASE_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '🧹 Chores'
    labels:
      - 'chore'
  - title: '📚 Documentation'
    labels:
      - 'docs'
  - title: '💅 Styles'
    labels:
      - 'style'
  - title: '♻️ Refactoring'
    labels:
      - 'refactor'
  - title: '⚡️ Performance'
    labels:
      - 'perf'
  - title: '🧪 Tests'
    labels:
      - 'test'
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  Thanks to everyone who contributed to this release:
  $CONTRIBUTORS
