name: Build and Test Main Branch

on:
  push:
    branches: [ main ]

jobs:
  build-test-main:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install .NET Framework 4.7.2 Developer Pack
      run: choco install netfx-4.7.2-devpack
      
    - name: Install npm dependencies
      working-directory: example/Example.RxDBClient
      run: npm install

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test ./tests/RxDBDotNet.Tests/RxDBDotNet.Tests.csproj --no-restore --verbosity normal
