name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Install .NET Framework 4.7.2 Developer Pack to build the client example app
      run: |
        wget https://download.visualstudio.microsoft.com/download/pr/9a1a5c45-09b2-4bbd-8a44-0638a6b2bc0f/2f5dcd31160f25762868d0cc58220013/ndp472-devpack-enu.exe
        sudo wine ndp472-devpack-enu.exe /quiet /norestart
        
    - name: Install .NET Aspire workload
      run: dotnet workload install aspire

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test ./tests/RxDBDotNet.Tests/RxDBDotNet.Tests.csproj --no-restore --verbosity normal

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2

    - name: Display Version
      run: |
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"