name: Pull Request

on:
  pull_request:
    branches: [ main ]
    types: [opened, reopened, synchronize]

jobs:
  build-and-test-pr:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install .NET Framework 4.7.2 Developer Pack
      run: choco install netfx-4.7.2-devpack
      
    - name: Install npm dependencies
      working-directory: example/Example.RxDBClient
      run: npm install

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test ./tests/RxDBDotNet.Tests/RxDBDotNet.Tests.csproj --no-restore --verbosity normal
      
    - name: Auto-label the PR
      uses: release-drafter/release-drafter@v5
      with:
        config-name: release-drafter.yml
        # We only want the auto-labeling feature.
        # The release will get drafted when the PR is merged to main.
        disable-releaser: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
