name: Determine Version

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  determine-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'

    - name: Determine the semantic version of this build
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.10.2

    # - name: Create tag
    #   run: git tag v${{ steps.gitversion.outputs.FullSemVer }}
    #   if: github.ref == 'refs/heads/main'
    # - name: Push tag
    #   run: git push origin v${{ steps.gitversion.outputs.FullSemVer }}
    #   if: github.ref == 'refs/heads/main'
